apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-kafka-deploy-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: strimzi
    name: in-cluster
  project: strimzi-project-dev
  source:
    path: kafka/deploy
    repoURL: https://github.com/dfollereau/argocd
    targetRevision: master